language: java


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew fatJar

before_deploy:
  - export RELEASE=$TRAVIS_TAG.$TRAVIS_BUILD_NUMBER

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "$TRAVIS_BUILD_DIR/build/libs/osmtoolsreader-all-$RELEASE.jar"
  skip_cleanup: true
  on:
    tags: true


